[package]
name = "log-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "52.2.0"
chrono = "0.4.38"
parquet = "52.2.0"
serde_json = "1.0.127"


[build-dependencies]
tonic-build = "0.12.2"
